apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: catalina.test
  namespace: sainsburys
spec:
  kafkaRestClassRef:
    name: krc-cfk
  replicas: 1
  partitionCount: 1
  configs:
    cleanup.policy: "delete"