apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: demo-topic
  namespace: sainsburys-poc
spec:
  kafkaClusterRef:
    name: kafka
    namespace: sainsburys-poc
  replicas: 1
  partitionCount: 1
  configs:
    cleanup.policy: "delete"
    retention.ms: "604800000"  # Retain messages for 7 days
    segment.bytes: "1073741824"  # Segment size of 1GB